import React from "react"
import styled from "styled-components"

const Wrapper = styled.div`
 background: #ECEFF1; 
 color: rgba(0,0,0,0.87); 
 font-family: Roboto, Helvetica, Arial, sans-serif; 
 margin: 0; 
 
 padding: 0; 

`
const MessageContainer = styled.div`
 background: white; max-width: 360px; margin: 100px auto 16px; padding: 32px 24px 16px; border-radius: 3px;
`

const NotFound = () => {
    return (
        <Wrapper>
            <MessageContainer>
                <h2 style={{ color: '#ffa100', fontWeight: 'bold', fontSize: '16px', margin: '0 0 8px' }}>404</h2>
                <h1 style={{ fontSize: '22px', fontWeight: '300', color: 'rgba(0,0,0,0.6)', margin: '0 0 16px' }}>Page Not Found</h1>
                <p style={{ lineHeight: '140%', margin: '16px 0 24px', fontSize: '14px' }}>The specified file was not found on this website. Please check the URL for mistakes and try again.</p>
                <h3 style={{ color: '#888', fontWeight: 'normal', fontSize: '16px', margin: '16px 0 12px' }}>Why am I seeing this?</h3>
                <p style={{ lineHeight: '140%', margin: '16px 0 24px', fontSize: '14px' }} >This page was generated by the Firebase Command-Line Interface. To modify it, edit the <code>404.html</code> file in your project's configured <code>public</code> directory.</p>


            </MessageContainer>
        </Wrapper>
    )


}


export default NotFound